sudo: false

language: go

go:
  - 1.9.x
  - 1.x

git:
  depth: 1

install: true

before_script:
  - go get -u github.com/golang/dep/cmd/dep
  - go get -u github.com/mgechev/revive
  - go get golang.org/x/tools/cover
  - go get golang.org/x/tools/cmd/cover
  - dep ensure

script:
  - revive -exclude ./vendor/... ./...
  - go test -race -coverprofile=coverage.txt -covermode=atomic

after_success:
  - bash <(curl -s "https://codecov.io/bash")
