language: go
sudo: false
dist: trusty
go:
  - 1.x
env:
  global:
    - GO111MODULE=on

before_install:
  - find "${GOPATH%%:*}" -name '*.a' -delete
  - rm -rf "${GOPATH%%:*}/src/golang.org"
  - go get golang.org/x/tools/cover
  - go get golang.org/x/tools/cmd/cover

before_script:
  - go mod download
  - go install github.com/golangci/golangci-lint/cmd/golangci-lint

script:
  - golangci-lint run
  - go test -race -coverprofile=coverage.txt -covermode=atomic

after_success:
  - bash <(curl -s "https://codecov.io/bash")

before_deploy:
  - mkdir -p release
  - GOOS=linux GOARCH=amd64 go build -ldflags "-X main.version=$TRAVIS_TAG" -o release/ksd-linux-amd64
  - GOOS=linux GOARCH=386 go build -ldflags "-X main.version=$TRAVIS_TAG" -o release/ksd-linux-386
  - GOOS=linux GOARCH=arm go build -ldflags "-X main.version=$TRAVIS_TAG" -o release/ksd-linux-arm
  - GOOS=darwin GOARCH=amd64 go build -ldflags "-X main.version=$TRAVIS_TAG" -o release/ksd-darwin-amd64

deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  skip_cleanup: true
  keep_history: true
  file:
  - release/ksd-linux-amd64
  - release/ksd-linux-386
  - release/ksd-linux-arm
  - release/ksd-darwin-amd64
  on:
    repo: mfuentesg/ksd
    tags: true
