on: release
name: Build
jobs:
  release-linux-386:
    name: release linux/386
    runs-on: ubuntu-latest
    steps:
      - name: Query version number
        id: get_version
        shell: bash
        run: |
          echo "using version tag ${GITHUB_REF:10}"
          echo ::set-output name=version::"${GITHUB_REF:10}"
      - uses: actions/checkout@master
      - name: compile and release
        uses: ngs/go-release.action@v1.0.1
        env:
          VERSION: ${{ steps.get_version.outputs.VERSION }}
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
          GOARCH: "386"
          GOOS: linux
  release-linux-amd64:
    name: release linux/amd64
    runs-on: ubuntu-latest
    steps:
      - name: Query version number
          id: get_version
          shell: bash
          run: |
            echo "using version tag ${GITHUB_REF:10}"
            echo ::set-output name=version::"${GITHUB_REF:10}"
      - uses: actions/checkout@master
      - name: compile and release
        uses: ngs/go-release.action@v1.0.1
        env:
          VERSION: ${{ steps.get_version.outputs.VERSION }}
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
          GOARCH: amd64
          GOOS: linux
  release-darwin-386:
    name: release darwin/386
    runs-on: ubuntu-latest
    steps:
      - name: Query version number
          id: get_version
          shell: bash
          run: |
            echo "using version tag ${GITHUB_REF:10}"
            echo ::set-output name=version::"${GITHUB_REF:10}"
      - uses: actions/checkout@master
      - name: compile and release
        uses: ngs/go-release.action@v1.0.1
        env:
          VERSION: ${{ steps.get_version.outputs.VERSION }}
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
          GOARCH: "386"
          GOOS: darwin
  release-darwin-amd64:
    name: release darwin/amd64
    runs-on: ubuntu-latest
    steps:
      - name: Query version number
          id: get_version
          shell: bash
          run: |
            echo "using version tag ${GITHUB_REF:10}"
            echo ::set-output name=version::"${GITHUB_REF:10}"
      - uses: actions/checkout@master
      - name: compile and release
        uses: ngs/go-release.action@v1.0.1
        env:
          VERSION: ${{ steps.get_version.outputs.VERSION }}
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
          GOARCH: amd64
          GOOS: darwin
  release-windows-386:
    name: release windows/386
    runs-on: ubuntu-latest
    steps:
      - name: Query version number
          id: get_version
          shell: bash
          run: |
            echo "using version tag ${GITHUB_REF:10}"
            echo ::set-output name=version::"${GITHUB_REF:10}"
      - uses: actions/checkout@master
      - name: compile and release
        uses: ngs/go-release.action@v1.0.1
        env:
          VERSION: ${{ steps.get_version.outputs.VERSION }}
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
          GOARCH: "386"
          GOOS: windows
  release-windows-amd64:
    name: release windows/amd64
    runs-on: ubuntu-latest
    steps:
      - name: Query version number
          id: get_version
          shell: bash
          run: |
            echo "using version tag ${GITHUB_REF:10}"
            echo ::set-output name=version::"${GITHUB_REF:10}"
      - uses: actions/checkout@master
      - name: compile and release
        uses: ngs/go-release.action@v1.0.1
        env:
          VERSION: ${{ steps.get_version.outputs.VERSION }}
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
          GOARCH: amd64
          GOOS: windows