name: ci

on:
  push:
    tags:
      - 'v*'

jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Unshallow
        run: git fetch --prune --unshallow
      - name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.x
      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v1
        with:
          version: latest
          args: release --config=.goreleaser.yml --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
          VERSION: ${{ steps.get_version.outputs.VERSION }}